### ISSUE TITLE
charter school feeds

### ISSUE THREAD

**Issue by katerabinowitz** [codefordc/school-modernization#8]
do charter schools have a feed pattern like DC public schools?

**Comment by coachpacman** [comment]
They don't. I will take a look at your other comments soon but in the mean
time big thank you for all this work!

On Wednesday, December 23, 2015, Kate Rabinowitz notifications@github.com
wrote:

> do charter schools have a feed pattern like DC public schools?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codefordc/school-modernization/issues/8.

## 

Tim Lee

**Comment by katerabinowitz** [comment]
No problem, I think we were originally thinking of visualizing the schools by their feed patterns, but if this doesn't apply to charters we might want to consider wards or some other higher level grouping
